config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :restaurants do
    resources :reviews
  end
  root 'restaurants#index'

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  validates :name,    presence: true
  validates :tel,     presence: true
  validates :address, presence: true


  has_many :reviews
  has_many :users, through: :reviews

  def average_satisfaction(restaurant_id)
    if Review.where(restaurant_id: restaurant_id).count > 0
      Review.where(restaurant_id: restaurant_id).average(:satisfaction)
    else
      return 0
    end
  end

  def average_satisfaction_star(restaurant_id)
  if Review.where(restaurant_id: restaurant_id).count > 0
    if Review.where(restaurant_id: restaurant_id).average(:satisfaction) == 5
        return "★★★★★"
      elsif Review.where(restaurant_id: restaurant_id).average(:satisfaction) >= 4
        return "★★★★☆"
      elsif Review.where(restaurant_id: restaurant_id).average(:satisfaction) >= 3
        return "★★★☆☆"
      elsif Review.where(restaurant_id: restaurant_id).average(:satisfaction) >= 2
        return "★★☆☆☆"
      else Review.where(restaurant_id: restaurant_id).average(:satisfaction) >= 1
        return "★☆☆☆☆"
      end
    else
      return "☆☆☆☆☆"
    end
  end

end

app/models/review.rb
class Review < ActiveRecord::Base
  validates :body,         presence: true
  validates :satisfaction, presence: true

  belongs_to :user
  belongs_to :restaurant

  def satisfaction_star(score)
    if score == 5
      return "★★★★★"
    elsif score >= 4
      return "★★★★☆"
    elsif score >= 3
      return "★★★☆☆"
    elsif score >= 2
      return "★★☆☆☆"
    elsif score >= 1
      return "★☆☆☆☆"
    else
      return "☆☆☆☆☆"
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :reviews
  has_many :restaurants, through: :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  protected
    def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:sign_up) << :gender
    devise_parameter_sanitizer.for(:sign_up) << :age
    devise_parameter_sanitizer.for(:account_update) << :name
    devise_parameter_sanitizer.for(:account_update) << :gender
    devise_parameter_sanitizer.for(:account_update) << :age
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :authenticate_user!

  def index
    @restaurants = Restaurant.page(params[:page])
    if current_user.name.include?("kodama")||current_user.name.include?("Kodama")||current_user.name.include?("KODAMA")||current_user.name.include?("小玉")||current_user.name.include?("こだま")||current_user.name.include?("コダマ")||current_user.gender == false
 #     @picture = "female2.jpg"
      @class = "img1"
    else
#       @picture = "hooters1.jpg"
       @class= "img2"
    end
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
    redirect_to restaurant_url(@restaurant)
    else
    render :new
    end
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    if @restaurant.update(restaurant_params)
      redirect_to restaurant_url(@restaurant)
    else
      render :edit
    end

  end

  def destroy

  end

  private

  def restaurant_params
    params.require(:restaurant).permit(
      :name,
      :tel,
      :address,
      :web_url
      )
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(
      restaurant_id: params[:restaurant_id],
      user_id: current_user.id,
      body: review_params["body"],
      satisfaction: review_params["satisfaction"].to_i
      )
    if @review.save
      redirect_to restaurant_url(@review.restaurant)
    else
      render :new
    end
  end

  def edit
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.find(params[:id])
  end

  def update
    @review = Review.find(params[:id])

    if @review.update(
      body: review_params["body"],
      satisfaction: review_params["satisfaction"].to_i
      )
      redirect_to restaurant_url(@review.restaurant)
    else
      render :edit
    end
  end

  def destroy
    @review = Review.find(params[:id])
    restaurant_id = @review.restaurant_id
    @review.destroy
    redirect_to restaurant_url(restaurant_id)

  end

  private
  def review_params
    params.require(:review).permit(
      :body,
      :satisfaction
      )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-menu">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/restaurants"><span class="glyphicon glyphicon-cutlery logo" aria-hidden="true"></span>  スパル食べログ  <span class="glyphicon glyphicon-cutlery logo" aria-hidden="true"></span></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="navbar-collapse-menu">

        <% if user_signed_in? %>
        <p class="navbar-text">
          <%= current_user.name %>さん ようこそ！
        </p>
        <ul class="nav navbar-nav navbar-right">
        <li><%= link_to '設定変更', edit_user_registration_path %></li>
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
        </ul>
        <% else %>
        <ul class="nav navbar-nav navbar-right">
        <li><%= link_to '新規登録', new_user_registration_path %></li>
        <li><%= link_to 'ログイン', new_user_session_path %></li>
        <% end %>
        </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SpartaTabelog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
  <% if notice.present? %>
    <div class="alert alert-dismissable alert-success">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <p><%= notice %></p>
    </div>
  <% end %>

  <% if alert.present? %>
    <div class="alert alert-dismissable alert-danger">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <p><%= alert %></p>
    </div>
  <% end %>
<%= yield %>
</div>
</body>
</html>

app/views/restaurants/_form.html.erb
<%= form_for @restaurant do |f| %>
  <div class="form-group">
    <%= f.label :name, "店名" %>
    <%= f.text_field :name, autofocus: true, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :tel, "電話番号" %>
    <%= f.text_field :tel, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :address, "住所" %>
    <%= f.text_field :address, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :web_url, "ホームページ" %>
    <%= f.text_field :web_url, class: "form-control" %>
  </div>

    <%= f.submit "登録する", class: "btn btn-default" %>

<% end %>

app/views/restaurants/edit.html.erb
<div class="row">
  <div class="col-lg-12">
    <h2>レストラン情報の編集</h2>
    <%= render 'form' %>
  </div>
</div>

app/views/restaurants/index.html.erb
<div class= "sidebar float-right">
     <img src="<%= asset_path "hooters_girl3.jpg" %>", class="<%= @class %>">
</div>
    <% @restaurants.each do |restaurant| %>
    <div class=" col-md-7 restaurants-index float-left">
      <h4><%= link_to restaurant.name, restaurant_url(restaurant) %></h4><br />
      <h4><%= restaurant.average_satisfaction_star(restaurant) %>
      <%= number_with_precision(restaurant.average_satisfaction(restaurant), precision: 1) %></h4><br />
      <% restaurant.reviews.each_with_index do |review, index| %>
      <%
        if index >= 1
          break
        end
        %>
      <%= truncate(review.body, length:200) %>
      <%= link_to '続きはこちら', restaurant_path(restaurant) %><br />
      <% end %>
    </div>
    <% end %>

<div class=" col-md-7 restaurants-index float-left">
    <%= link_to '新しいレストランの情報を投稿する', new_restaurant_path, class: "btn btn-default" %>
</div>
<div class=" col-md-7 float-left">
<%= paginate @restaurants %>
</div>

app/views/restaurants/new.html.erb
<div class="row">
  <div class="col-lg-12">
  <h2>レストラン情報の新規登録</h2>
    <%= render 'form' %>

  </div>
</div>

app/views/restaurants/show.html.erb
<div class="row">
  <div class="col-lg-12">
    <h3><%= @restaurant.name %></h3><br />
    <h4><%= @restaurant.average_satisfaction_star(@restaurant) %>
      <%= number_with_precision(@restaurant.average_satisfaction(@restaurant), precision: 1) %></h4><br />
    電話番号 : <%= @restaurant.tel %><br />
    住所 : <%= @restaurant.address %><br />
    ホームページ : <a href="<%= @restaurant.web_url %>"><%= @restaurant.web_url %></a><br />
  </div>
</div>
<hr>
<div class="row">
  <div class="col-lg-12">
    <%= link_to "このお店のレビューを書く", new_restaurant_review_path(@restaurant), class: "btn btn-default" %>
  </div>
</div>
<hr>
<div class="row">
  <div class="col-lg-12">
    <h2>レビュー一覧</h2>
      <hr>
    <% @restaurant.reviews.each do |review| %>
      <%= review.satisfaction_star(review.satisfaction) %>  <%= number_with_precision(review.satisfaction, precision: 1) %><br />
      <%= simple_format(review.body) %><br />
      <%= review.user.name %> |
      <%= review.created_at.strftime("%Y年%m月%d日") %><br />
      <% if current_user.id == review.user_id %>
      <%= link_to '編集', edit_restaurant_review_path(@restaurant, review) %> |
       <a href="#" data-toggle="modal" data-target="#delete-review">削除</a><br />
               <!-- モーダル -->
        <div class="modal fade" id="delete-review">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">レビューの削除</h4>
              </div>
              <div class="modal-body">
                <p>このレビューを削除しますか？</p>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">キャンセル</button>
                <%= link_to '削除する',restaurant_review_path(@restaurant, review),method: :delete, class: "btn btn-danger" %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
      <hr>
    <% end %>
  </div>
</div>

app/views/reviews/_form.html.erb
<%= form_for [@restaurant, @review] do |f| %>
<div class="form-group">
  <%= f.label :body, "レビュー" %>
  <%= f.text_area :body, class: "form-control" %>
<div>

<div class="form-group">
  <%= f.label :satisfaction, "満足度" %>
  <%= f.number_field :satisfaction, class: "form-control" %>
<div>

  <%= f.submit '投稿', class: "btn btn-default" %>
<% end %>

app/views/reviews/edit.html.erb
<h1>レビューを編集する</h1>
<ul>
  <li>お店名:<%= @restaurant.name %></li>
</ul>
<%= render 'form' %>

app/views/reviews/new.html.erb
<h1>レビュー登録</h1>
<ul>
  <li>お店名:<%= @restaurant.name %></li>
</ul>
<%= render 'form' %>